# Generated by Django 4.2.10 on 2025-03-25 16:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200, unique=True)),
                ('main_image', cloudinary.models.CloudinaryField(default='placeholder-home', max_length=255, verbose_name='image')),
                ('property_type', models.IntegerField(choices=[(0, 'Detached House'), (1, 'Semi-Detached House'), (2, 'Terraced House'), (3, 'Apartment'), (4, 'Flat'), (5, 'Studio Apartment'), (6, 'Penthouse'), (7, 'Townhouse')], default=0)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('garage', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('listed_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-listed_on'],
            },
        ),
    ]
