# Generated by Django 4.2.10 on 2024-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-listed_on'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
