# Generated by Django 4.2.10 on 2024-02-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='address',
        ),
    ]
