# Generated by Django 4.2.10 on 2024-02-21 22:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_location_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='placeholder-home', max_length=255, verbose_name='image'),
        ),
    ]
