# Generated by Django 4.2.10 on 2024-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(default='Title', max_length=200, unique=True),
        ),
    ]
